#ifndef DIO_CONFIG_H_
#define DIO_CONFIG_H_
/* Macros For Pins */
/* Select Direction Pins :DIO_U8_INTIAL_OUTPUT
                           DIO_U8_INTIAL_INTPUT */
/* PORTA */
#define DIO_U8_PA0_INTIAL_DIRECTION				DIO_U8_INTIAL_INTPUT
#define DIO_U8_PA1_INTIAL_DIRECTION				DIO_U8_INTIAL_INTPUT
#define DIO_U8_PA2_INTIAL_DIRECTION				DIO_U8_INTIAL_OUTPUT
#define DIO_U8_PA3_INTIAL_DIRECTION				DIO_U8_INTIAL_OUTPUT
#define DIO_U8_PA4_INTIAL_DIRECTION				DIO_U8_INTIAL_OUTPUT
#define DIO_U8_PA5_INTIAL_DIRECTION				DIO_U8_INTIAL_OUTPUT
#define DIO_U8_PA6_INTIAL_DIRECTION				DIO_U8_INTIAL_OUTPUT
#define DIO_U8_PA7_INTIAL_DIRECTION				DIO_U8_INTIAL_OUTPUT
/* PORTB */
#define DIO_U8_PB0_INTIAL_DIRECTION				DIO_U8_INTIAL_OUTPUT
#define DIO_U8_PB1_INTIAL_DIRECTION				DIO_U8_INTIAL_OUTPUT
#define DIO_U8_PB2_INTIAL_DIRECTION				DIO_U8_INTIAL_OUTPUT
#define DIO_U8_PB3_INTIAL_DIRECTION				DIO_U8_INTIAL_OUTPUT
#define DIO_U8_PB4_INTIAL_DIRECTION				DIO_U8_INTIAL_OUTPUT
#define DIO_U8_PB5_INTIAL_DIRECTION				DIO_U8_INTIAL_OUTPUT
#define DIO_U8_PB6_INTIAL_DIRECTION				DIO_U8_INTIAL_OUTPUT
#define DIO_U8_PB7_INTIAL_DIRECTION             DIO_U8_INTIAL_OUTPUT
/* PORTC */
#define DIO_U8_PC0_INTIAL_DIRECTION				DIO_U8_INTIAL_OUTPUT
#define DIO_U8_PC1_INTIAL_DIRECTION				DIO_U8_INTIAL_OUTPUT
#define DIO_U8_PC2_INTIAL_DIRECTION				DIO_U8_INTIAL_OUTPUT
#define DIO_U8_PC3_INTIAL_DIRECTION				DIO_U8_INTIAL_OUTPUT
#define DIO_U8_PC4_INTIAL_DIRECTION				DIO_U8_INTIAL_OUTPUT
#define DIO_U8_PC5_INTIAL_DIRECTION				DIO_U8_INTIAL_OUTPUT
#define DIO_U8_PC6_INTIAL_DIRECTION				DIO_U8_INTIAL_OUTPUT
#define DIO_U8_PC7_INTIAL_DIRECTION             DIO_U8_INTIAL_OUTPUT
/* PORTD */
#define DIO_U8_PD0_INTIAL_DIRECTION				DIO_U8_INTIAL_OUTPUT
#define DIO_U8_PD1_INTIAL_DIRECTION				DIO_U8_INTIAL_OUTPUT
#define DIO_U8_PD2_INTIAL_DIRECTION				DIO_U8_INTIAL_OUTPUT
#define DIO_U8_PD3_INTIAL_DIRECTION				DIO_U8_INTIAL_OUTPUT
#define DIO_U8_PD4_INTIAL_DIRECTION				DIO_U8_INTIAL_OUTPUT
#define DIO_U8_PD5_INTIAL_DIRECTION				DIO_U8_INTIAL_OUTPUT
#define DIO_U8_PD6_INTIAL_DIRECTION				DIO_U8_INTIAL_OUTPUT
#define DIO_U8_PD7_INTIAL_DIRECTION			    DIO_U8_INTIAL_OUTPUT

/* Select Value Pins : DIO_U8_OUTPUT_HIGH 
                       DIO_U8_INTPUT_LOW 
					   DIO_U8_INPUT_FLOTING
					   DIO_U8_INPUT_PULLUP   */
/* PORTA */
#define DIO_U8_PA0_INTIAL_VALUE				DIO_U8_INPUT_FLOTING 
#define DIO_U8_PA1_INTIAL_VALUE				DIO_U8_INPUT_FLOTING 
#define DIO_U8_PA2_INTIAL_VALUE				DIO_U8_INPUT_FLOTING
#define DIO_U8_PA3_INTIAL_VALUE				DIO_U8_INPUT_FLOTING 
#define DIO_U8_PA4_INTIAL_VALUE				DIO_U8_INPUT_FLOTING
#define DIO_U8_PA5_INTIAL_VALUE				DIO_U8_INPUT_FLOTING
#define DIO_U8_PA6_INTIAL_VALUE				DIO_U8_INPUT_FLOTING
#define DIO_U8_PA7_INTIAL_VALUE				DIO_U8_INPUT_FLOTING
/* PORTB */                            
#define DIO_U8_PB0_INTIAL_VALUE				DIO_U8_INPUT_FLOTING
#define DIO_U8_PB1_INTIAL_VALUE				DIO_U8_INPUT_FLOTING
#define DIO_U8_PB2_INTIAL_VALUE				DIO_U8_INPUT_FLOTING
#define DIO_U8_PB3_INTIAL_VALUE				DIO_U8_INPUT_FLOTING
#define DIO_U8_PB4_INTIAL_VALUE				DIO_U8_INPUT_FLOTING
#define DIO_U8_PB5_INTIAL_VALUE				DIO_U8_INPUT_FLOTING
#define DIO_U8_PB6_INTIAL_VALUE				DIO_U8_INPUT_FLOTING
#define DIO_U8_PB7_INTIAL_VALUE             DIO_U8_INPUT_FLOTING
/* PORTC */                            
#define DIO_U8_PC0_INTIAL_VALUE				DIO_U8_INPUT_FLOTING
#define DIO_U8_PC1_INTIAL_VALUE				DIO_U8_INPUT_FLOTING
#define DIO_U8_PC2_INTIAL_VALUE				DIO_U8_INPUT_FLOTING
#define DIO_U8_PC3_INTIAL_VALUE				DIO_U8_INPUT_FLOTING
#define DIO_U8_PC4_INTIAL_VALUE				DIO_U8_INPUT_FLOTING
#define DIO_U8_PC5_INTIAL_VALUE				DIO_U8_INPUT_FLOTING
#define DIO_U8_PC6_INTIAL_VALUE				DIO_U8_INPUT_FLOTING
#define DIO_U8_PC7_INTIAL_VALUE             DIO_U8_INPUT_FLOTING
/* PORTD */                            
#define DIO_U8_PD0_INTIAL_VALUE				DIO_U8_INPUT_FLOTING
#define DIO_U8_PD1_INTIAL_VALUE				DIO_U8_INPUT_FLOTING
#define DIO_U8_PD2_INTIAL_VALUE				DIO_U8_INPUT_FLOTING
#define DIO_U8_PD3_INTIAL_VALUE				DIO_U8_INPUT_FLOTING
#define DIO_U8_PD4_INTIAL_VALUE				DIO_U8_INPUT_FLOTING
#define DIO_U8_PD5_INTIAL_VALUE				DIO_U8_INPUT_FLOTING
#define DIO_U8_PD6_INTIAL_VALUE				DIO_U8_INPUT_FLOTING
#define DIO_U8_PD7_INTIAL_VALUE			    DIO_U8_INPUT_FLOTING
#endif
